#!/bin/bash

# Network access point
ssid=$(nmcli device show | awk 'NR==6' | awk '{print $2}')

# Wifi status (enabled/disabled)
wifi_status=$(echo $(nmcli -fields WIFI g | awk 'NR==2'))

if [[ "$wifi_status" = "desactivado" ]]; then
	echo %{F#ff85cb}"󱛅  X "%{F-}
else

	if [[ "$ssid" = "lo" ]]; then
		echo %{F#ff85cb}"󰖪 "%{F-}
	else
		echo %{F#ff85cb}"  $ssid"%{F-}
	fi
fi
